### ISSUE TITLE
Development setup issues

### ISSUE THREAD

**Issue by gius** [josejulio/openapi2typescript#2]
When cloning the repo, there are the following issues:

1. `yarn install` fails. `yarnPath` from `.yarnrc.yml` leads to a non-existent location.
2. 'prepare' script fails because Husky is missing as a `devDependency`.
3. Prettier is not configured and thus default IDE prettier plugin rules conflict with eslint (tabsize, quotes, etc.)
4. Eslint rule for line endings complicate development on Windows. It should be handled by Git (https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems)

**Comment by josejulio** [comment]
#13 and #12 should have fixed the remaining issues.
