### ISSUE TITLE
Add support for skipping export module Schemas

### ISSUE THREAD

**Issue by Lonli-Lokli** [josejulio/openapi2typescript#6]
Right now the following lines are generated
```
import * as z from 'zod';

export module Schemas {
```

First of all, better way for import will be `import { z } from 'zod';`, second - typescript modules or namespaces are often should be omitted.
Can new option --schemaDeclaration with values 'none' | 'module' be added? And with 'none' no `export module Schemas` should be added to output

**Comment by josejulio** [comment]
I guess we could work out something here.
I'm using the Schemas because a plugin also adds
`export module Operations {` to namespace all the operations.

ummmh, probably could consolidate all into the top level.

**Comment by josejulio** [comment]
I've decided to remove the `export module` when not using an actionGenerator - as I guess this is the usual for people only wanting the zod schema out of the openapi.

**Comment by Lonli-Lokli** [comment]
Thanks for fixing his, but did you publish the latest version with the fix?
